Team Member Card View is completed.
BaNSC/bansc.github.io pull request #1
Opened 2020-09-24 05:54 UTC by Rishabh3321

Card Design Link [https://codepen.io/fikirkod/pen/PoYVymv](url)
Modify/Add into teamMermberData for adding/editing more Members.

2020-09-24 07:42 UTC, Sharma-Hrishabh commented
The cards are looking great. But it will be better if you could just shift the content of the about us page into the home page.
Keep the spacing in mind while moving the content in to the homepage :)

2020-09-24 07:42 UTC, Sharma-Hrishabh reviewed
LGTM

2020-09-24 14:03 UTC, Rishabh3321 commented
New changes 
- Content of About is now under Home Page.
- Line height and font size changes for increasing readability
- Join link underline and out of button clickable fixes.

Fonts, line-height, etc. are subjective. Suggestions will be welcome.

2020-09-24 17:32 UTC, Sharma-Hrishabh requested changes
LGTM except one thing. There should be more spacing between different sections viz. Landing, About and Team.
It will be good, if only one section is visible at once, and other appears after one scroll.

2020-09-30 23:50 UTC, Rishabh3321 commented
I have changed the height to the full viewport. But it is looking a little bit extra spacious. We should add more content to justify its full viewport or reduce the space to some scale.

2020-10-07 14:17 UTC, Ujjwal0501 commented on src/portofolio_sections/AboutContent.jsx
> +  height: 100vh;
making every division's height equal to the screen height is not a good decision.

It introduces unnecessary extra space.
![image](https://user-images.githubusercontent.com/31813384/95343114-c7ea2800-08d5-11eb-9256-779e4f243db2.png)

2020-10-07 14:26 UTC, Ujjwal0501 approved these changes, later dismissed

2020-10-07 14:26 UTC, Ujjwal0501 commented on src/portofolio_sections/AboutContent.jsx
> +        <Col className="mt-2 p-0">
Using `mt-#` and `p-#` classes is the better way to add spacing between div.

2020-10-07 15:01 UTC, Ujjwal0501 commented
I think we can separately accept changes from commit [`dd5cb24` (#1)](https://github.com/BaNSC/bansc.github.io/pull/1/commits/dd5cb248744aa3189989c4073ca79bc41c3b3158) and a change for adding spacing in a way I suggested above.

Rishabh will have to pick that change and create a new PR. And also add the suggested spacing.

The changes related to Card View can be put into separate PR.

So I suggest the following:
1. Split this PR into two separate PRs
2. First PR will include changes from [`dd5cb24` (#1)](https://github.com/BaNSC/bansc.github.io/pull/1/commits/dd5cb248744aa3189989c4073ca79bc41c3b3158) + spacing related changes
3. Second PR will include changes from [`c567615` (#1)](https://github.com/BaNSC/bansc.github.io/pull/1/commits/c5676153a4554a1ac912e6a9988a74011e362b3e)
The card view will further need some changes so a separate PR is better.

2020-10-07 16:39 UTC, Sharma-Hrishabh commented
Agree @Ujjwal0501. The branch is deviating far from the current-branch. So, creating a separate PR will serve the propose and we can merge the first PR, till you proceed with your work on the second one.

2020-10-31 12:54 UTC, Sharma-Hrishabh commented
Closed via #3

2020-10-31 12:54 UTC, closed without merging